apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipeline
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/afrog33k/digital-ocean-k8s-challenge
    targetRevision: HEAD
    path: manifests/tekton-pipeline/

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-argocd-pipeline
