apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myblog
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/nandajavarma/blog
    targetRevision: HEAD
    path: deployment

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
