---
apiVersion: v1
kind: Secret
metadata:
  name: basic-git-app-repo-user-pass
  annotations:
    tekton.dev/git-0: https://github.com/nandajavarma/blog
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7InVzZXJuYW1lIjoiNGU4YzRiZTYzYjkwYmU1ODk0MDMyYjdkNzJiNTRmZjkxZDBhNThiYThhM2ViMmM4Mjk3OGI5NDdkNjdiNDU1ZCIsInBhc3N3b3JkIjoiNGU4YzRiZTYzYjkwYmU1ODk0MDMyYjdkNzJiNTRmZjkxZDBhNThiYThhM2ViMmM4Mjk3OGI5NDdkNjdiNDU1ZCIsImF1dGgiOiJOR1U0WXpSaVpUWXpZamt3WW1VMU9EazBNRE15WWpka056SmlOVFJtWmpreFpEQmhOVGhpWVRoaE0yVmlNbU00TWprM09HSTVORGRrTmpkaU5EVTFaRG8wWlRoak5HSmxOak5pT1RCaVpUVTRPVFF3TXpKaU4yUTNNbUkxTkdabU9URmtNR0UxT0dKaE9HRXpaV0l5WXpneU9UYzRZamswTjJRMk4ySTBOVFZrIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: basic-docker-user-pass
  annotations:
    tekton.dev/docker-0: registry.digitalocean.com
type: kubernetes.io/dockerconfigjson
